# Generated by Django 4.0.3 on 2022-06-25 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='emotionalbeing',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='gratitude',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='physicalbeing',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('I', 'IMPORTANT'), ('U', 'URGENT'), ('C', 'CASUAL')], max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('COM', 'COMPLETED'), ('PEN', 'PENDING'), ('MIG', 'MIGRATED'), ('CAN', 'CANCELLED')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
