# Generated by Django 4.0.3 on 2022-06-25 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_task_emotionalbeing_task_gratitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotionalbeing', models.TextField(null=True)),
                ('physicalbeing', models.TextField(null=True)),
                ('gratitude', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('I', 'IMPORTANT'), ('U', 'URGENT'), ('C', 'CASUAL')], max_length=1)),
                ('status', models.CharField(choices=[('COM', 'COMPLETED'), ('PEN', 'PENDING'), ('MIG', 'MIGRATED'), ('CAN', 'CANCELLED')], default='PEN', max_length=3)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
