# Generated by Django 4.0.3 on 2022-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_taskchecklist_tasktodolist_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchecklist',
            name='emotionalbeing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='gratitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='physicalbeing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
