# Generated by Django 4.0.3 on 2022-06-26 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_taskchecklist_emotionalbeing_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskchecklist',
            unique_together={('user', 'date')},
        ),
    ]
